# Generated by Django 2.2.6 on 2019-12-05 21:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 21, 13, 1, 603136, tzinfo=utc))),
                ('characterName', models.CharField(max_length=52)),
                ('playerName', models.CharField(max_length=52)),
                ('Class', models.TextField()),
                ('race', models.TextField()),
                ('background', models.TextField()),
                ('level', models.IntegerField()),
                ('alignment', models.TextField()),
                ('experience', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('strengthMod', models.IntegerField()),
                ('dexterityMod', models.IntegerField()),
                ('constitutionMod', models.IntegerField()),
                ('intelligenceMod', models.IntegerField()),
                ('wisdomMod', models.IntegerField()),
                ('charismaMod', models.IntegerField()),
                ('racialFeatures', models.TextField()),
                ('classFeatures', models.TextField()),
                ('backgroundFeatures', models.TextField()),
                ('armorClass', models.IntegerField()),
                ('initiative', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('maxHitPoints', models.IntegerField()),
                ('hitDiceAmount', models.IntegerField()),
                ('hitDiceType', models.IntegerField()),
                ('proficiencyBonus', models.IntegerField()),
                ('strengthSavePro', models.BooleanField()),
                ('dexteritySavePro', models.BooleanField()),
                ('constitutionSavePro', models.BooleanField()),
                ('intelligenceSavePro', models.BooleanField()),
                ('wisdomSavePro', models.BooleanField()),
                ('charismaSavePro', models.BooleanField()),
                ('acrobaticsPro', models.BooleanField()),
                ('animalHandlingPro', models.BooleanField()),
                ('arcanaPro', models.BooleanField()),
                ('athleticsPro', models.BooleanField()),
                ('deceptionPro', models.BooleanField()),
                ('historyPro', models.BooleanField()),
                ('insightPro', models.BooleanField()),
                ('intimidationPro', models.BooleanField()),
                ('investigationPro', models.BooleanField()),
                ('medicinePro', models.BooleanField()),
                ('naturePro', models.BooleanField()),
                ('perceptionPro', models.BooleanField()),
                ('performancePro', models.BooleanField()),
                ('persuasionPro', models.BooleanField()),
                ('religionPro', models.BooleanField()),
                ('sleightOfHandPro', models.BooleanField()),
                ('stealthPro', models.BooleanField()),
                ('survivalPro', models.BooleanField()),
                ('personalityTraits', models.TextField()),
                ('ideals', models.TextField()),
                ('bonds', models.TextField()),
                ('flaws', models.TextField()),
                ('featuresAndTraits', models.TextField()),
                ('weapons', models.TextField()),
                ('armor', models.TextField()),
                ('miscEquipment', models.TextField()),
                ('money', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
